name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy via Rsync with Password Authentication
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete \
            --rsh="ssh -p 65002 u309746653@154.56.33.55" \
            --exclude 'api/' \
            dist/ \
            hostinger:/domains/lapinou.tech/public_html/
